Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MEGATECH.Models;
using MEGATECH.Models.EF;

namespace MEGATECH.Controllers
{
    public class MenuController : Controller
    {
        private MEGATECHDBContext db = new MEGATECHDBContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTop()
        {
            var items = db.categories
                .Where(x => x.IsActive)
                .OrderBy(x => x.Position).ToList();
            return PartialView("_MenuTop", items);
        }

        public ActionResult MenuProductCategory()
        {
            var items = db.productCategories.ToList();
            return PartialView("_MenuProductCategory", items);
        }
        public ActionResult MenuLeft(string id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.productCategories.ToList();
            return PartialView("_MenuLeft", items);
        }

        public ActionResult MenuSupplier(string id)
        {
            if (id != null)
            {
                ViewBag.SupplierId = id;
            }
            var items = db.nhaCungCaps.ToList();
            return PartialView("_MenuSupplier", items);
        }

        public ActionResult MenuArrivals()
        {
            var items = db.productCategories.ToList();
            return PartialView("_MenuArrivals", items);
        }

    }
}

Controllers/TimKiemController.cs
using MEGATECH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MEGATECH.Controllers
{
    public class TimKiemController : Controller
    {
        private MEGATECHDBContext db = new MEGATECHDBContext();
        // GET: TimKiem
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string searchString)
        {
            ViewBag.searchString = searchString;
            var items = db.products.ToList();
            var product = items.Where(p => p.Title.ToLower().Contains(searchString.ToLower()));
            if (product != null)
            {
                return View(product);
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using MEGATECH.Common
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="MEGATECH">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/bootstrap4/bootstrap.min.css">
    <link href="~/Content/assets/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
    <meta name="description" content="@ViewBag.SeoDescription" />
    <meta name="keywords" itemprop="keywords" content="@ViewBag.SeoKeyWord" />
    @*<meta name="news_keywords" content="@ViewBag.SeoKeyWord" />*@
    <link rel="canonical" href="https://www.megatech.com/" />
    <meta name="robots" content="index,follow,noodp" />
    <meta name="robots" content="noarchive">
    <meta property="og:site_name" content="MEGATECH" />
    <meta property="og:type" content="Website" />
    <meta property="og:locale" content="vi_VN" />
    <meta property="og:title" itemprop="name" content="@ViewBag.Title" />
    <meta property="og:url" itemprop="url" content="https://www.megatech.com/" />
    <meta property="og:description" content="@ViewBag.SeoDescription" />
    <meta content="https://cdn.24h.com.vn/upload/2-2018/images/2018-06-14/logo-chan-trang-24h.png" property="og:image" itemprop="thumbnailUrl" />
    <!--script_breadcrum-->
    @*@RenderSection("css", required: false)*@
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/responsive.css">
    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>

    <style>
        .navbar_user li a:hover {
            text-decoration: none;
        }

        #search-box {
            background: #fff;
            border-radius: 30px;
        }

            #search-box #search-text {
                border: none;
                outline: none;
                background: none;
                font-size: 18px;
                width: 0;
                padding: 0;
                transition: all 0.25s ease-in-out;
            }

                #search-box:hover #search-text, #search-box #search-text:valid {
                    width: 300px;
                    padding: 10px 15px 10px 15px;
                    border: 1px solid #ccc;
                    border-radius: 8px;
                }

            #search-box i {
                background-color: none;
                border: none;
                cursor: pointer;
                font-size: 18px;
            }
    </style>
    <div class="super_container">
        <!-- Header -->
        <header class="header trans_300">

            <!-- Top Navigation -->

            <div class="top_nav">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="top_nav_left">Hotline: 0938279950</div>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="top_nav_left">Email: daota311280@sv-onuni.edu.vn</div>
                        </div>
                        @*<div class="col-md-6 text-right">
                                <div class="top_nav_right">
                                    <ul class="top_nav_menu">
                                        <li class="account">
                                            @if (!Request.IsAuthenticated)
                                            {
                                                <a href="#">
                                                    My Account
                                                    <i class="fa fa-angle-down"></i>
                                                </a>
                                                <ul class="account_selection">
                                                    <li><a href="/account/login"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
                                                    <li><a href="/account/Register"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
                                                </ul>
                                            }
                                            else
                                            {
                                                <a href="#">
                                                    Welcome: @User.Identity.Name
                                                    <i class="fa fa-angle-down"></i>
                                                </a>
                                                <ul class="account_selection">
                                                    <li><a href="/account/profile"><i class="fa fa-sign-in" aria-hidden="true"></i>Profile</a></li>
                                                    <li><a href="/wishlist/index"><i class="fa fa-sign-in" aria-hidden="true"></i>Sản phẩm yêu thích</a></li>
                                                    <li><a href="javascript:document.getElementById('logOffForm').submit()"><i class="fa fa-user-plus" aria-hidden="true"></i> Logout</a></li>
                                                </ul>
                                            }

                                        </li>
                                    </ul>

                                    @if (Request.IsAuthenticated)
                                    {
                                        <div style="display:none">
                                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { @id = "logOffForm" }))
                                            {
                                                @Html.AntiForgeryToken()
                                            }
                                        </div>
                                    }
                                </div>
                            </div>*@
                    </div>
                </div>
            </div>
            <!-- Main Navigation -->
            <div class="main_nav_container">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="logo_container">
                                <a href="/">
                                    <img src="~/Images/logov.png" width="150" />
                                </a>
                            </div>
                            <nav class="navbar">
                                @Html.Action("MenuTop", "Menu")
                                <ul class="navbar_user">
                                    <li class="li_search mr-3">
                                        <form action="@Url.Action("Index","TimKiem")" method="post" id="search-box">
                                            <input type="text" id="search-text" name="searchString" placeholder="Nhập tên sản phẩm bạn cần tìm" required>
                                            <i class="fa fa-search"></i>
                                        </form>
                                    </li>

                                    <li class="checkout">
                                        <a href="/gio-hang">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                            <span id="checkout_items" class="checkout_items">0</span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="hamburger_container">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

        </header>

        @RenderBody()

    </div>

    <script src="~/Content/assets/styles/bootstrap4/popper.js"></script>
    <script src="~/Content/assets/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="~/Content/assets/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="~/Content/assets/plugins/easing/easing.js"></script>
    <script src="~/Content/assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <script src="~/Content/assets/js/custom.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jsShopping.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>