Areas/Admin/Controllers/SupplierController.cs
using MEGATECH.App_Start;
using MEGATECH.Models;
using MEGATECH.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MEGATECH.Areas.Admin.Controllers
{
    public class SupplierController : Controller
    {
        private MEGATECHDBContext db = new MEGATECHDBContext();

        private List<NhaCungCap> getList(string viewName, List<NhaCungCap> filteredList)
        {
            if (filteredList != null && filteredList.Any())
            {
                // Sử dụng danh sách đã lọc nếu có
                return filteredList;
            }

            // Nếu không có danh sách đã lọc, trả về danh sách mặc định
            return db.nhaCungCaps.OrderBy(x => x.Title).ToList();
        }
        //Hiển thị danh sách toàn bộ: SELCT * FROM
        public List<NhaCungCap> getList(string status = "All")
        {
            List<NhaCungCap> list = null;
            switch (status)
            {
                case "Index":
                    {
                        list = db.nhaCungCaps
                            .Where(m => m.Status != 0)
                            .ToList();
                        break;
                    }
                case "Trash":
                    {
                        list = db.nhaCungCaps
                            .Where(m => m.Status == 0)
                            .ToList();
                        break;
                    }
                default:
                    {
                        list = db.nhaCungCaps.OrderBy(x => x.Title).ToList();
                        break;
                    }
            }
            return list;
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_XemDanhSach", chucVu = "Quản lý")]

        public ActionResult Index(string Searchtext)
        {
            // Khởi tạo danh sách nhân viên và sắp xếp theo ID giảm dần
            var items = db.nhaCungCaps.AsQueryable();

            // Kiểm tra nếu có chuỗi tìm kiếm
            if (!string.IsNullOrEmpty(Searchtext))
            {
                // Lọc danh sách theo các tiêu chí tìm kiếm
                items = items.Where(x =>
                    x.MaNhaCungCap.Contains(Searchtext) ||
                    x.Title.Contains(Searchtext) ||
                    x.SoDienThoai.Contains(Searchtext) ||
                    x.Email.Contains(Searchtext)
                );
            }
            // Chỉ lấy những nhân viên có status != 0
            items = items.Where(x => x.Status != 0);
            // Chuyển danh sách đã lọc sang getList để trả về kết quả
            var filteredList = items.OrderByDescending(x => x.MaNhaCungCap).ToList(); // Chuyển đổi IQueryable thành List
            var resultList = getList("Index", filteredList);

            return View(resultList);
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_ThemMoi", chucVu = "Quản lý")]
        public ActionResult Create()
        {
            return View();
        }
        [AdminAuthorize(idChucNang = "MEGATECH_ThemMoi", chucVu = "Quản lý")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NhaCungCap model)
        {
            if (ModelState.IsValid)
            {
                var exist = db.nhaCungCaps.FirstOrDefault(x => x.Title == model.Title);
                if (exist != null)
                {
                    ModelState.AddModelError("Title", "Tên nhà cung cấp đã tồn tại.");
                    // Trả về View với model để hiển thị lỗi
                    return View(model);
                }
                const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
                var random = new Random();
                var mancc = new string(Enumerable.Repeat(chars, 8)
                    .Select(s => s[random.Next(s.Length)]).ToArray());
                model.MaNhaCungCap = mancc;
                model.CreatedBy = "MEGATECH Administrator";
                model.CreatedDate = DateTime.Now;
                model.Alias = MEGATECH.Models.Common.Filter.FilterChar(model.Title);
                model.Status = 1;
                db.nhaCungCaps.Add(model);
                db.SaveChanges();
                //Hiển thị thông báo thành công
                TempData["message"] = new XMessage("success", "Thêm mới nhà cung cấp  " + model.Title + " thành công");
                return RedirectToAction("Index");
            }
            return View();
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_ChinhSua", chucVu = "Quản lý")]
        public ActionResult Edit(string id)
        {
            var item = db.nhaCungCaps.Find(id);
            return View(item);
        }
        [AdminAuthorize(idChucNang = "MEGATECH_ChinhSua", chucVu = "Quản lý")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NhaCungCap model)
        {
            if (ModelState.IsValid)
            {
                // Cập nhật thông tin của tài khoản
                model.Modifiedby = "MEGATECH Administrator";
                model.ModifiedDate = DateTime.Now;
                model.Alias = MEGATECH.Models.Common.Filter.FilterChar(model.Title);
                db.nhaCungCaps.Attach(model);
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();

                //Hiển thị thông báo thành công
                TempData["message"] = new XMessage("success", "Chỉnh sửa thông tin nhà cung cấp " + model.Title + " thành công");
                return RedirectToAction("Index");
            }
            return View();
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_XemChiTiet", chucVu = "Quản lý")]
        public ActionResult Detail(string id)
        {
            var item = db.nhaCungCaps.Find(id);
            return View(item);
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_Xoa", chucVu = "Quản lý")]
        public ActionResult Trash()
        {
            return View(getList("Trash"));
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_Xoa", chucVu = "Quản lý")]
        public ActionResult GoToTrash(string id)
        {
            if (id == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Đưa nhà cung cấp có id " + id + " vào thùng rác thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }

            var item = db.nhaCungCaps.Find(id);
            if (item == null)
            {
                //Thông báo thất bại
                TempData["message"] = new XMessage("danger", "Đưa nhà cung cấp " + item.Title + " vào thùng rác thất bại");
                //Chuyển hướng trang
                return RedirectToAction("Index");
            }
            item.Status = 0;
            db.Entry(item).State = EntityState.Modified;
            db.SaveChanges();
            //Hiển thị thông báo thành công
            TempData["message"] = new XMessage("success", "Đưa thành công nhà cung cấp " + item.Title + " vào thùng rác");
            //Trở về trang Index
            return RedirectToAction("Index");
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_Xoa", chucVu = "Quản lý")]
        [HttpPost]
        public ActionResult GoToTrashAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var obj = db.nhaCungCaps.Find(item);
                        if (obj != null)
                        {
                            obj.Status = 0;
                            db.Entry(obj).State = EntityState.Modified;
                        }
                    }
                    db.SaveChanges();
                }
                //Hiển thị thông báo thành công
                TempData["message"] = new XMessage("success", "Đưa thành công các nhà cung cấp đã lựa chọn vào thùng rác");
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_Xoa", chucVu = "Quản lý")]
        public ActionResult Delete(string id)
        {
            var item = db.nhaCungCaps.Find(id);
            if (item == null)
            {
                //Hiển thị thông báo
                TempData["message"] = new XMessage("danger", "Không tìm thấy nhà cung cấp có id " + item.MaNhaCungCap);
                // Nếu không tìm thấy Menu, trả về lỗi
                return RedirectToAction("Index");
            }
            db.nhaCungCaps.Remove(item);
            db.SaveChanges();
            //Hiển thị thông báo
            TempData["message"] = new XMessage("success", "Xoá thành công nhà cung cấp " + item.Title);
            return Json(new { success = true });
        }
        ///////////////////////////////////////////////////////////////////////////////////////
        [AdminAuthorize(idChucNang = "MEGATECH_Xoa", chucVu = "Quản lý")]
        [HttpPost]

Areas/Admin/Views/Supplier/Create.cshtml
@model MEGATECH.Models.EF.NhaCungCap

@{
    ViewBag.Title = "Thêm mới nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="page-title">Thêm mới nhà cung cấp</h4>
                    </div>
                    <div class="col-md-6 text-right">
                        <ul class="breadcrumbs">
                            <li class="nav-home">
                                <a href="@Url.Action("Index", "Home")">
                                    <i class="flaticon-home"></i>
                                </a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Supplier")">Danh sách nhà cung cấp</a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="#">Thêm mới</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("Create", "Supplier", FormMethod.Post, new { }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <!-- your steps content here -->
                            <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Tên nhà cung cấp <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Nhập tên nhà cung cấp" })
                                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Alias</label>
                                            @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Nhập Alias" })
                                            @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group form-group-default">
                                            <label>Số điện thoại <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @placeholder = "Nhập số điện thoại nhà cung cấp" })
                                            @Html.ValidationMessageFor(x => x.SoDienThoai, null, new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group form-group-default">
                                            <label>Email <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "Nhập Email" })
                                            @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Hình ảnh nhà cung cấp</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(x => x.Image, new { @id = "txtImage", @class = "form-control", @readonly = "readonly" })
                                                </div>
                                                <div class="input-group-append col-md-2">
                                                    <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage');" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Title</label>
                                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control", @placeholder = "Nhập Seo Title" })
                                            @Html.ValidationMessageFor(x => x.SeoTitle, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Description</label>
                                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control", @placeholder = "Nhập Seo Description" })
                                            @Html.ValidationMessageFor(x => x.SeoDescription, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Keywords</label>
                                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control", @placeholder = "Nhập Seo Keywords" })
                                            @Html.ValidationMessageFor(x => x.SeoKeywords, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-success">Thêm mới</button>
                                    <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger">Quay lại</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.content -->
@section  scripts{


    <script src="~/Scripts/jsConvert.js"></script>

    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}

Areas/Admin/Views/Supplier/Detail.cshtml
@model MEGATECH.Models.EF.NhaCungCap
@{
    ViewBag.Title = "Chi tiết danh mục nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="page-title">Chi tiết thông tin nhà cung cấp: @Model.Title</h4>
                    </div>
                    <div class="col-md-6 text-right">
                        <ul class="breadcrumbs">
                            <li class="nav-home">
                                <a href="@Url.Action("Index", "Home")">
                                    <i class="flaticon-home"></i>
                                </a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Supplier")">Danh sách nhà cung cấp</a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="#">Xem chi tiết</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group form-group-default">
                                        <label>Tên nhà cung cấp</label>
                                        <span class="form-control">@Model.Title</span>
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Alias</label>
                                        <span class="form-control">@Model.Alias</span>
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Số điện thoại</label>
                                        <span class="form-control">@Model.SoDienThoai</span>
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Email</label>
                                        <span class="form-control">@Model.Email</span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group form-group-default text-center">
                                        <label>Hình ảnh nhà cung cấp</label><br />
                                        @if (!string.IsNullOrEmpty(Model.Image))
                                        {
                                            <img src="@Model.Image" alt="Ảnh sản phẩm" width="200" class="img-fluid">
                                        }
                                        else
                                        {
                                            <span class="form-control">Chưa thêm ảnh cho nhà cung cấp này</span>
                                        }
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Seo Title</label>
                                        <textarea class="form-control">@Model.SeoTitle</textarea>
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Seo Description</label>
                                        <textarea class="form-control">@Model.SeoDescription</textarea>
                                    </div>
                                    <div class="form-group form-group-default">
                                        <label>Seo Keywords</label>
                                        <textarea class="form-control">@Model.SeoKeywords</textarea>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="form-group text-center">
                            <a href="/admin/supplier/edit/@Model.MaNhaCungCap" class="btn btn-primary">Vào trang chỉnh sửa</a>
                            <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger">Quay lại</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Supplier/Edit.cshtml
@model MEGATECH.Models.EF.NhaCungCap

@{
    ViewBag.Title = "Chỉnh sửa thông tin nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="page-title">Chỉnh sửa thông tin nhà cung cấp: @Model.Title</h4>
                    </div>
                    <div class="col-md-6 text-right">
                        <ul class="breadcrumbs">
                            <li class="nav-home">
                                <a href="@Url.Action("Index", "Home")">
                                    <i class="flaticon-home"></i>
                                </a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Supplier")">Danh sách nhà cung cấp</a>
                            </li>
                            <li class="separator">
                                <i class="flaticon-right-arrow"></i>
                            </li>
                            <li class="nav-item">
                                <a href="#">Chỉnh sửa</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @using (Html.BeginForm("Edit", "Supplier", FormMethod.Post, new { }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(x => x.MaNhaCungCap)
                            @Html.HiddenFor(x => x.Status)
                            @Html.HiddenFor(x => x.CreatedBy)
                            @Html.HiddenFor(x => x.CreatedDate)
                            <!-- your steps content here -->
                            <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Tên nhà cung cấp <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Nhập tên nhà cung cấp" })
                                            @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Alias <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Nhập Alias" })
                                            @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group form-group-default">
                                            <label>Số điện thoại <span class="text-danger">*</span></label>
                                            @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @placeholder = "Nhập số điện thoại nhà cung cấp" })
                                            @Html.ValidationMessageFor(x => x.SoDienThoai, null, new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group form-group-default">
                                            <label>Email <span class="text-danger">*</span></label>
                                            @Html.TextAreaFor(x => x.Email, new { @class = "form-control", @placeholder = "Nhập Email" })
                                            @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group form-group-default">
                                            <label>Hình ảnh nhà cung cấp</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(x => x.Image, new { @id = "txtImage", @class = "form-control", @readonly = "readonly" })
                                                </div>
                                                <div class="input-group-append col-md-2">
                                                    <input type="button" value="Tải ảnh" onclick="BrowseServer('txtImage');" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Title</label>
                                            @Html.TextAreaFor(x => x.SeoTitle, new { @class = "form-control", @placeholder = "Nhập Seo Title" })
                                            @Html.ValidationMessageFor(x => x.SeoTitle, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Description</label>
                                            @Html.TextAreaFor(x => x.SeoDescription, new { @class = "form-control", @placeholder = "Nhập Seo Description" })
                                            @Html.ValidationMessageFor(x => x.SeoDescription, null, new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group form-group-default">
                                            <label>Seo Keywords</label>
                                            @Html.TextAreaFor(x => x.SeoKeywords, new { @class = "form-control", @placeholder = "Nhập Seo Keywords" })
                                            @Html.ValidationMessageFor(x => x.SeoKeywords, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit" class="btn btn-primary">Chỉnh sửa</button>
                                    <a href="@Url.Action("Index", "Supplier")" class="btn btn-danger">Quay lại</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.content -->
@section  scripts{

    <script src="~/Scripts/jsConvert.js"></script>

    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtDetail', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}